- hosts: home-lab1
  become: true
  tasks:
    - name: Stop and disable nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: no

    - name: Remove nginx package
      ansible.builtin.apt:
        name: nginx
        state: absent
        purge: yes

    - name: Delete index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Remove nginx config
      ansible.builtin.file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Clean apt cache
      ansible.builtin.apt:
        autoclean: yes
